name: music_play
description: A music player app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
repository: "https://github.com/hakouklvn/musicPlayer.git"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^8.3.0
  google_fonts: ^2.2.0
  audio_service: ^0.18.3
  just_audio: ^0.9.18
  get_it: ^7.2.0
  rive: ^0.7.22
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  app_settings: ^4.1.1
  on_audio_query: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
