name: mousika
description: A music player app.
publish_to: "none"
version: 1.0.0+1
repository: "https://github.com/hakouklvn/mousika.git"

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^9.2.0
  google_fonts: ^3.0.1
  audio_service: ^0.18.3
  just_audio: ^0.9.18
  get_it: ^7.2.0
  rive: ^0.8.4
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  app_settings: ^4.1.1
  on_audio_query: ^2.6.0
  sleek_circular_slider: ^2.0.1
  flutter_riverpod: ^1.0.4
  hive_flutter: ^1.1.0
  hive: ^2.2.2
  flutter_local_notifications: ^9.6.1
  dynamic_color: ^1.5.4

dependency_overrides:
  material_color_utilities: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
